version: 2
jobs:
  build:
    working_directory: /go/src/github.com/anthdm/hbbft
    docker:
      - image: vidsyhq/go-builder:latest
        environment:
          BUILD: false
    steps:
      - checkout
      - restore_cache:
          key: "dependency-cache-vendor-{{ checksum \"Gopkg.lock\" }}"
      - run: /scripts/build.sh
      - save_cache:
        key: "dependency-cache-vendor-{{ checksum \"Gopkg.lock\" }}"
        paths:
          - vendor
          - /go/pkg
  test:
    working_directory: /go/src/github.com/anthdm/hbbft
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: "dependency-cache-vendor-{{ checksum \"Gopkg.lock\" }}"
      - run: go test

workflows:
  version: 2
  build_test:
    jobs:
      - build:
        filters:
          tags:
            only: /[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: master
        - test:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master